name: Conventional Commits

on:
  workflow_call:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ubiquity/action-conventional-commits@master