name: Knip

on:
  workflow_call:
    inputs:
        pr_number:
            required: true
            type: string

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Store PR number
        run: echo ${{ inputs.pr_number }} > pr-number.txt

      - name: Run Knip
        run: bun run knip || bun run knip-ci > knip-results.json

      - name: Upload knip result
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: knip-results
          path: |
            knip-results.json
            pr-number.txt