name: Knip-reporter

on:
  workflow_call:
    inputs:
        workflow-run-id:
            required: true
            type: string
        workflow:
            required: true
            type: string
    secrets:
        GITHUB_TOKEN:
            required: true

jobs:
  knip-reporter:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: knip-results
          run-id: ${{ inputs.workflow-run-id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read pr number
        id: pr-number
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pr-number.txt
          trim: true

      - name: Report knip results to pull request
        uses: ubiquity/knip-reporter@main
        with:
          verbose: true
          comment_id: ${{ inputs.workflow }}-reporter
          command_script_name: knip-ci
          annotations: true
          ignore_results: false
          json_input: true
          json_input_file_name: knip-results.json
          pull_request_number: ${{ steps.pr-number.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}